name: Android Lint

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run Ktlint
        uses: lucasnlm/ktlint-action@master